apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: canary-demo
spec:
  args:
  - name: service-name
  - name: namespace
  metrics:
  - name: success-rate
    interval: 30s
    successCondition: result[0] >= 0.95
    count: 5
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          sum(irate(
            istio_requests_total{
              reporter="source",
              destination_service=~"{{args.service-name}}.*",
              destination_service_namespace="{{args.namespace}}",
              destination_version="canary",
              response_code!~"5.*"
            }[2m]
          )) /
          sum(irate(
            istio_requests_total{
              reporter="source",
              destination_service=~"{{args.service-name}}.*",
              destination_service_namespace="{{args.namespace}}",
              destination_version="canary"
            }[2m]
          ))
