apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: canary-demo
spec:
  args:
  - name: service-name
  - name: namespace
  metrics:
  - name: success-rate
    interval: 30s
    count: 3
    successCondition: result[0] >= 0.95
    failureCondition: result[0] < 0.95
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          sum(
            rate(istio_requests_total{
              reporter="destination",
              destination_service="{{args.service-name}}.{{args.namespace}}.svc.cluster.local",
              response_code!~"5.*"
            }[1m])
          )
          /
          sum(
            rate(istio_requests_total{
              reporter="destination",
              destination_service="{{args.service-name}}.{{args.namespace}}.svc.cluster.local"
            }[1m])
          )
