apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: canary-demo
spec:
  args:
  - name: service-name
    value: my-app
  - name: namespace
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  metrics:
  - name: success-rate
    interval: 30s
    successCondition: result[0] >= 0.95
    failureCondition: result[0] < 0.95
    provider:
      prometheus:
        address: http://prometheus.istio-system:9090
        query: |
          sum(rate(istio_requests_total{
            destination_service_name="{{args.service-name}}",
            destination_service_namespace="{{args.namespace}}",
            response_code!~"5.*"
          }[1m]))
          /
          sum(rate(istio_requests_total{
            destination_service_name="{{args.service-name}}",
            destination_service_namespace="{{args.namespace}}"
          }[1m]))