---
apiVersion: v1
kind: Namespace
metadata:
  name: canary-demo
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: my-app
  namespace: canary-demo
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: my-app
  namespace: canary-demo
spec:
  host: my-app
  subsets:
  - name: stable
    labels:
      app: my-app
  - name: canary
    labels:
      app: my-app
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-app
  namespace: canary-demo
spec:
  hosts:
  - my-app
  http:
  - name: http 
    route:
    - destination:
        host: my-app
        subset: stable
      weight: 100
    - destination:
        host: my-app
        subset: canary
      weight: 0
