---
apiVersion: v1
kind: Service
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: my-app
spec:
  host: my-app
  subsets:
  - name: stable
    labels:
      version: green
  - name: canary
    labels:
      version: red
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-app
spec:
  hosts:
  - my-app
  http:
  - name: default
    route:
    - destination:
        host: my-app
        subset: stable
      weight: 100
    - destination:
        host: my-app
        subset: canary
      weight: 0
