apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: my-app
  namespace: canary-demo
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: argoproj/rollouts-demo:blue
        ports:
        - containerPort: 8080
  strategy:
    canary:
      trafficRouting:
        istio:
          virtualService:
            name: my-app
            routes:
            - http
          destinationRule:
            name: my-app
            stableSubsetName: stable
            canarySubsetName: canary
      maxSurge: 1
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - analysis:
          templates:
          - templateName: success-rate
          args:
          - name: namespace
            value: canary-demo
          - name: service-name
            value: my-app
      - pause: { duration: 1m }
      - setWeight: 30
      - pause: { duration: 1m }
      - setWeight: 50
      - pause: { duration: 1m }
      - setWeight: 80
      - pause: { duration: 1m }
